version: '3.4'

services:
  test-build-v1:
    image: test-build-v1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV= production
    ports:
      - 3000:3000
