jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.FE_JOURNEY_AWS }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add SSH known hosts
      run: |
        ssh-keyscan -H 3.0.139.123 >> ~/.ssh/known_hosts

    - name: Build and Deploy to EC2
      run: |
        # Build production files
        npm run build
        
        # List files in dist folder before deploying
        ls -l dist/

        # Deploy files to EC2
        ssh -i ~/.ssh/id_rsa ubuntu@3.0.139.123 << 'EOF'
          cd /home/ubuntu/fe-journey
          git pull origin master
          npm install
          npm run build
          
          # Check contents of dist directory on EC2
          ls -l /home/ubuntu/fe-journey/dist/
          
          sudo rm -rf /var/www/html/*
          sudo cp -r /home/ubuntu/fe-journey/dist/* /var/www/html/
          sudo systemctl restart nginx
        EOF
