name: Deploy to EC2

on:
  push:
    branches:
      - master  # Chạy khi push lên nhánh master

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build the project
        run: |
          echo "VITE_HOST_BACKEND=${{ secrets.VITE_HOST_BACKEND }}" > .env
          cat .env  # Kiểm tra biến môi trường
          npm run build

      - name: Deploy dist folder to EC2
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.FE_JOURNEY_AWS }}
          REMOTE_HOST: "3.0.139.123"
          REMOTE_USER: "ubuntu"
          SOURCE: "dist/"
          TARGET: "/home/ubuntu/fe-journey"
          SCRIPT_AFTER: |
            sudo rm -rf /var/www/html/*
            sudo mv /home/ubuntu/fe-journey/* /var/www/html/
            sudo systemctl restart nginx
