name: Deploy to EC2

on:
  push:
    branches:
      - master  # Deploy khi push lên nhánh master

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build the project
        run: |
          echo "VITE_HOST_BACKEND=${{ secrets.VITE_HOST_BACKEND }}" >> .env
          echo "VITE_HOST_WEBSOCKET=${{ secrets.VITE_HOST_WEBSOCKET }}" >> .env
          npm ci
          npm run build

      - name: Deploy dist folder to EC2
        run: |
          # Cấu hình SSH để kết nối với EC2
          mkdir -p ~/.ssh
          echo "${{ secrets.FE_JOURNEY_AWS }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "3.0.139.123" >> ~/.ssh/known_hosts  # Hard-code host của EC2

          # Sao chép dist/ lên EC2
          scp -r ./dist/* ubuntu@3.0.139.123:/home/ubuntu/fe-journey/dist

          # Khởi động lại ứng dụng trên EC2
          ssh ubuntu@3.0.139.123 << 'EOF'
            # Dọn dẹp thư mục cũ trên server
            sudo rm -rf /var/www/html/*

            # Sao chép các file từ /home/ubuntu/fe-journey vào thư mục web của Nginx
            sudo cp -r /home/ubuntu/fe-journey/dist/* /var/www/html/

            # Restart Nginx
            sudo systemctl restart nginx
          EOF
